name: CI/CD Pipeline with Firebase App Distribution

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'  # Updated to Flutter 3.10 or higher (which includes Dart SDK 3.5.4)

      - name: Verify Flutter version
        run: flutter --version  # This helps ensure the correct Flutter version is installed

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test # Optional: Add your test commands here

      - name: Build APK (for Android)
        run: flutter build apk --release

      - name: Set up Firebase CLI
        run: |
          curl -sL https://firebase.tools | bash
          firebase --version

      - name: Authenticate Firebase
        run: echo "${{ secrets.FIREBASE_SECRET }}" > ${HOME}/firebase-key.json
        env:
          FIREBASE_SECRET: ${{ secrets.FIREBASE_SECRET }}

      - name: Deploy to Firebase App Distribution (Android)
        run: |
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk --app <your_firebase_app_id> --groups <testers_group> --token ${{ secrets.FIREBASE_AUTH_TOKEN }}
        env:
          FIREBASE_AUTH_TOKEN: ${{ secrets.FIREBASE_AUTH_TOKEN }}
